name: Sync upstream repository

on:
  schedule:
    # 每天北京时间凌晨3点运行
    - cron: "0 19 * * *"

  workflow_dispatch:


permissions:
  contents: write


jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Sync upstream
        run: |
          git remote add upstream https://github.com/lzwme/chatgpt-nav.git

          git fetch upstream

          git checkout main

          git merge upstream/main

          git push origin main
